parserOptions:
    ecmaVersion: 2019
    sourceType: module

env:
    es6: true
    node: true

extends: eslint:recommended

rules:
    array-bracket-spacing: [2, never]
    block-scoped-var: 2
    brace-style: 2
    camelcase: [2, {properties: never}]
    comma-dangle: [2, never]
    comma-spacing: [2, {before: false, after: true}]
    comma-style: 2
    computed-property-spacing: 2
    consistent-return: 2
    consistent-this: [2, self]
    curly: 2
    dot-notation: 2
    eqeqeq: 2
    eol-last: 2
    guard-for-in: 1
    key-spacing: 2
    keyword-spacing: 2
    linebreak-style: 0
    new-cap: 2
    no-alert: 2
    no-array-constructor: 2
    no-caller: 2
    no-cond-assign: 2
    no-constant-condition: 2
    no-control-regex: 2
    no-console: 0
    no-debugger: 2
    no-delete-var: 2
    no-div-regex: 2
    no-dupe-keys: 2
    no-duplicate-case: 2
    no-empty-character-class: 2
    no-empty: 2
    no-ex-assign: 2
    no-extra-boolean-cast: 2
    no-extra-parens: 1
    no-extra-semi: 2
    no-func-assign: 2
    no-implicit-coercion: 2
    no-inner-declarations: 2
    no-invalid-regexp: 2
    no-irregular-whitespace: [2, {skipStrings: true, skipTemplates: true}]
    no-lonely-if: 2
    no-mixed-spaces-and-tabs: 2
    no-multiple-empty-lines: 2
    no-native-reassign: 2
    no-negated-condition: 2
    no-negated-in-lhs: 2
    no-new-object: 2
    no-new-wrappers: 2
    no-obj-calls: 2
    no-redeclare: 2
    no-regex-spaces: 2
    no-sequences: 2
    no-shadow: 0
    no-shadow-restricted-names: 2
    no-spaced-func: 2
    no-sparse-arrays: 2
    no-trailing-spaces: [2, {skipBlankLines: true}]
    no-undef: 2
    no-undef-init: 2
    no-unneeded-ternary: 2
    no-unused-expressions: 2
    no-unused-vars: 2
    no-unreachable: 2
    no-use-before-define: [2, nofunc]
    no-var: 2
    no-with: 2
    object-curly-spacing: 2
    one-var: [2, never]
    operator-linebreak: [error, after]
    prefer-const: 2
    quotes: [2, single]
    radix: 2
    semi: 2
    semi-spacing: 2
    space-before-blocks: 2
    space-before-function-paren: [2, {anonymous: always, named: never}]
    space-in-parens: 2
    space-infix-ops: 0
    use-isnan: 2
    valid-jsdoc: 2
    valid-typeof: 2
    no-unexpected-multiline: 2
